### ISSUE TITLE
Upload binaries

### ISSUE THREAD

**Issue by fanatid** [mafintosh/prebuildify#6]
Don't you mind if I do PR which adds option for upload binaries to github? After we can create package `prebuildify-download` (like [prebuild-install](https://github.com/mafintosh/prebuild-install))
This will helpful for #1

**Comment by fanatid** [comment]
@mafintosh re `prebuildify-ci`: should we add upload feature here or in `prebuildify-ci`? (I prefer here)

**Comment by mafintosh** [comment]
How would uploads/download work in general? The main idea here is that we bundle all prebuilds inside the tarball to avoid weird permission errors etc

**Comment by fanatid** [comment]
I thought that main benefit of `prebuildify` that bindings can work with any node/electron version. But of course prebuilds inside tarball is also important, because allow distribute bindings when user offline.

My thoughts about `prebuildify-ci`/`prebuildify-download`:
- `prebuildify-ci` determine that commit is release (new version in package.json) and build prebuilds with `prebuildify` and upload to github (with `prebuildify`?)
- if developer want distribute package with prebuilds in tarball he should download all prebuilds (windows/linux/mac) (`prebuildify-download --all` for example) and publish on npm
- if developer does not want distribute package with prebuilds in tarball he can publish package immediately and prebuilds will be downloaded with `prebuildify-download` when package will be installed or compiled with `node-gyp-build` if required version not found

**Comment by mafintosh** [comment]
We added all this in prebuildify-ci. Works really great.
